server:
  port: 8801

spring:
  application:
    name: cloudalibaba-seata-order-8801
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/seata_mall?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: root
      password: root@0123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_mall?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root@0123
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      ribbon:
        enabled: false
    alibaba:
      seata:
        tx-service-group: SEATA_GROUP # 事务组, 随便写
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


management:
  endpoint:
    web:
      exposure:
        include='*':
seata:
  tx-service-group: SEATA_GROUP # 事务组名称，要和服务端对应
  service:
    vgroup-mapping:
      SEATA_GROUP: default # key是事务组名称 value要和服务端的机房名称保持一致