server:
  port: 8802

spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/seata_mall?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
      username: root
      password: root@0123
  application:
    name: cloudalibaba-seata-stock-8802
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      ribbon:
        enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

management:
  endpoint:
    web:
      exposure:
        include='*':

